// ---------------------------------------------------------------------------
// Guest Mode — mock API layer
//
// Mirrors the shape of the real backend responses so pages that were built
// against axios + the real API keep working untouched when a visitor is
// browsing as a guest. Reads/writes the dataset generated by guestData.js.
// ---------------------------------------------------------------------------

import { getGuestData, setGuestData, genId } from './guestData';

const NETWORK_DELAY_MS = 300;

class MockApiError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

const toAxiosError = (err) => ({
  response: {
    status: err.status || 500,
    data: { success: false, error: err.message || 'Something went wrong' },
  },
});

const companyPublicView = (c) => ({
  _id: c._id,
  name: c.name,
  industry: c.industry,
  description: c.description,
  products: c.products,
  logoUrl: c.logoUrl,
  avatarColor: c.avatarColor,
  avatarText: c.avatarText,
  userId: { email: c.email },
});

const formValue = (form, key) => (form && typeof form.get === 'function' ? form.get(key) : undefined);

const handle = (method, url, body, data) => {
  const path = url.split('?')[0];

  // ---- Company -------------------------------------------------------
  if (method === 'get' && path === '/company/me') {
    return {
      success: true,
      _id: data.company._id,
      name: data.company.name,
      email: data.company.email,
      industry: data.company.industry,
      description: data.company.description,
      products: data.company.products,
      logoUrl: data.company.logoUrl,
      avatarColor: data.company.avatarColor,
      avatarText: data.company.avatarText,
    };
  }

  if (method === 'get' && path === '/company') {
    return [data.company, ...data.otherCompanies].map(companyPublicView);
  }

  const companyIdMatch = path.match(/^\/company\/([a-zA-Z0-9]+)$/);

  if (method === 'get' && companyIdMatch) {
    const all = [data.company, ...data.otherCompanies];
    const c = all.find((x) => x._id === companyIdMatch[1]);
    if (!c) throw new MockApiError(404, 'Company not found');
    return companyPublicView(c);
  }

  if (method === 'put' && companyIdMatch) {
    const name = formValue(body, 'name');
    const industry = formValue(body, 'industry');
    const description = formValue(body, 'description');
    let products;
    try {
      products = JSON.parse(formValue(body, 'products'));
    } catch {
      products = null;
    }

    if (name) data.company.name = name;
    if (industry) data.company.industry = industry;
    if (description) data.company.description = description;
    if (Array.isArray(products) && products.length) data.company.products = products.map((p) => p.trim()).filter(Boolean);

    // keep "created by" labels in sync with the renamed company
    data.myTenders.forEach((t) => {
      t.createdBy.name = data.company.name;
    });

    setGuestData(data);
    return { ...data.company };
  }

  if (method === 'post' && path === '/company/create') {
    // Guests already have a company profile generated for them.
    return { ...data.company };
  }

  // ---- Tenders --------------------------------------------------------
  if (method === 'post' && path === '/tender/create') {
    const { title, description, deadline, budget } = body || {};
    const newTender = {
      _id: genId(),
      title,
      description,
      deadline,
      budget: Number(budget),
      createdBy: { _id: data.company._id, name: data.company.name },
      status: 'open',
      createdAt: new Date().toISOString(),
    };
    data.myTenders.unshift(newTender);
    setGuestData(data);
    return newTender;
  }

  if (method === 'get' && path === '/tender/myTender') {
    return data.myTenders;
  }

  if (method === 'get' && path === '/tender/others') {
    return data.otherTenders;
  }

  const tenderIdMatch = path.match(/^\/tender\/([a-zA-Z0-9]+)$/);

  if (method === 'get' && tenderIdMatch) {
    const all = [...data.myTenders, ...data.otherTenders];
    const t = all.find((x) => x._id === tenderIdMatch[1]);
    if (!t) throw new MockApiError(404, 'Tender not found');
    return t;
  }

  if (method === 'put' && tenderIdMatch) {
    const idx = data.myTenders.findIndex((t) => t._id === tenderIdMatch[1]);
    if (idx === -1) throw new MockApiError(404, 'Tender not found or not authorized');
    data.myTenders[idx] = {
      ...data.myTenders[idx],
      ...body,
      budget: body?.budget !== undefined ? Number(body.budget) : data.myTenders[idx].budget,
    };
    setGuestData(data);
    return data.myTenders[idx];
  }

  if (method === 'delete' && tenderIdMatch) {
    const idx = data.myTenders.findIndex((t) => t._id === tenderIdMatch[1]);
    if (idx === -1) throw new MockApiError(404, 'Tender not found or not authorized');
    data.myTenders.splice(idx, 1);
    data.receivedApplications = data.receivedApplications.filter((a) => a.tenderId._id !== tenderIdMatch[1]);
    setGuestData(data);
    return { message: 'Tender deleted' };
  }

  // ---- Applications -----------------------------------------------------
  const applyMatch = path.match(/^\/application\/([a-zA-Z0-9]+)\/apply$/);

  if (method === 'post' && applyMatch) {
    const tender = data.otherTenders.find((t) => t._id === applyMatch[1]);
    if (!tender) throw new MockApiError(404, 'Tender not found');

    const { proposalText, bidAmount } = body || {};
    const newApp = {
      _id: genId(),
      tenderId: { _id: tender._id, title: tender.title, deadline: tender.deadline },
      proposalText,
      bidAmount: Number(bidAmount),
      status: 'pending',
    };
    data.myApplications.unshift(newApp);
    setGuestData(data);
    return newApp;
  }

  if (method === 'get' && path === '/application/my') {
    return data.myApplications;
  }

  if (method === 'get' && path === '/application/received') {
    return data.receivedApplications;
  }

  const approveMatch = path.match(/^\/application\/([a-zA-Z0-9]+)\/approve$/);

  if (method === 'put' && approveMatch) {
    const app = data.receivedApplications.find((a) => a._id === approveMatch[1]);
    if (!app) throw new MockApiError(404, 'Application not found');

    app.status = 'approved';
    data.receivedApplications.forEach((a) => {
      if (a.tenderId._id === app.tenderId._id && a._id !== app._id) a.status = 'rejected';
    });

    setGuestData(data);
    return { success: true, message: 'Application approved' };
  }

  throw new MockApiError(404, `No mock handler for ${method.toUpperCase()} ${path}`);
};

export const guestRequest = (method, url, body) =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      try {
        const data = getGuestData();
        if (!data) {
          reject(toAxiosError(new MockApiError(401, 'Your guest session has expired. Please continue as guest again.')));
          return;
        }
        const result = handle(method, url, body, data);
        resolve({ data: result });
      } catch (err) {
        reject(toAxiosError(err));
      }
    }, NETWORK_DELAY_MS);
  });
